services:
  - type: web
    name: flowise-of-ha
    runtime: node
    branch: flowise@3.0.4
    healthCheckPath: /api/v1/health
    instanceType: free
    buildCommand: "pnpm install && pnpm build"
    startCommand: "pnpm start"
    envVars:
      - key: FLOWISE_USERNAME
        sync: false
      - key: FLOWISE_PASSWORD
        sync: false
    disk:
      name: flowise-data
      mountPath: /opt/render/project/src/.flowise
      sizeGB: 1
